cc_library(
    name = "libvalfuzz",
    srcs = ["valfuzz.cpp"],
    hdrs = ["//include/valfuzz:valfuzz.hpp"],
    includes = ["//include"],
    copts = ["-Iinclude -std=c++23"],
    visibility = ["//visibility:public"],
)
